### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by D-X-Y** [layumi/matlab_email_demo#1]
牛，让我膜拜下！

**Comment by mychina75** [comment]
大牛版主，用voc2007训了ZF模型，很成功，但显示bbox有问题。
请帮我看看吧，多谢！

![test](https://cloud.githubusercontent.com/assets/798230/24195473/de73cd36-0f34-11e7-816a-8d4590af8701.JPG)

**Comment by D-X-Y** [comment]
你用的是哪个代码测试的？看上去好像没有用NMS？（这个问题不该在这个repo问吧。。

**Comment by mychina75** [comment]
汗...没找到入口，在Faster下面提示要到google论坛留言...

图片中的log是port到windows下面跑出来的。
以为是cpu部分代码的问题，就用您提供的example下面demo_frcnn.sh，在GPU上又跑，还是不对。
因为训练是用两块GPU训的，以为是并行出的错，改成单GPU训VGG16，结果还是不对。。。
又截了个gpu测试的图，请版主看看是参数设置的问题，还是哪的原因啊，多谢！
![test1](https://cloud.githubusercontent.com/assets/798230/24277767/420944a2-107a-11e7-9553-2abb4a45a9a4.JPG)
